// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PictureWipe","status":true,"description":"ピクチャの切り替えエフェクトです。","parameters":{}},
{"name":"NovelMessage","status":true,"description":"全画面型のメッセージウィンドウです。","parameters":{"Switch ID":"11"}},
{"name":"messagespeed","status":true,"description":"メッセージ速度調整プラグイン","parameters":{"表示速度変数":"1","瞬間表示":"OFF"}},
{"name":"CustomizeConfigItem","status":true,"description":"オプション任意項目作成プラグイン","parameters":{"スイッチ項目1":"足音:ON:4:ON","数値項目1":"メッセージ速度:2:1:ON:1:3:1","音量項目1":"","文字項目1":"","スイッチ項目2":"","数値項目2":"","音量項目2":"","文字項目2":""}},
{"name":"UTA_MessageSkip","status":true,"description":"特定キーを押す事でメッセージをスキップできるようにします。","parameters":{"Skip Key":"pageup","Show Trace":"false"}},
{"name":"OuterSelfSwitch","status":true,"description":"他のイベントのセルフスイッチを操作します。","parameters":{}},
{"name":"SymbolEncountLib","status":true,"description":"シンボルエンカウントを実装するためのライブラリです。","parameters":{}},
{"name":"TYA_SymbolEncount","status":true,"description":"シンボルエンカウント作成の補助を行います。\r\n詳しい使い方はヘルプを参照してください。","parameters":{"situationVariables":"20"}},
{"name":"AltMenuScreen","status":true,"description":"メニュー画面のレイアウトを変更します。","parameters":{}},
{"name":"Gamefocus","status":true,"description":"ゲームがアクティブウィンドウでなくなった際に、\r\nオーディオかビデオ、もしくはその両方を一時停止します。","parameters":{"Pause Audio":"true","Pause Graphics":"true"}}
];
